[theme]
base = "auto"
primaryColor = "#00B4DB"  # Azul vibrante (tarjetas, botones)
backgroundColor = "#ffffff"  # Claro por defecto
secondaryBackgroundColor = "#f0f2f6"  # Fondo sidebar claro
textColor = "#000000"
font = "sans serif"
